---
- name: Set pip_executable
  set_fact:
    pip_executable: pip3

- name: Find connection graph file
  set_fact:
    connection_graph_filename: "{{ lookup('graphfile', duts_name.split(',')) }}"

- name: Set connection db server hostname
  set_fact:
    connection_db_host: "{{ item.value }}"
  loop: "{{ connection_db_host_mapping | dict2items }}"
  when: item.key == connection_graph_filename

- name: Get connection db server ip
  set_fact:
    connection_db_host_ip: "{{ ansible_ssh_host }}"
  delegate_to: "{{ connection_db_host }}"

- name: Start connection database
  include_tasks: start_db.yml
  args:
    apply:
      delegate_to: "{{ connection_db_host }}"
      become: True
  when: action == 'start_db'

- name: Stop connection database
  include_tasks: stop_db.yml
  args:
    apply:
      delegate_to: "{{ connection_db_host }}"
      become: True
  when: action == 'stop_db'

- name: Start db provision
  include_tasks: start_provision_db.yml
  when: action == 'start_provision_db'
