name: $(Build.DefinitionName)_Running_Init_$(Build.BuildId)_$(Date:yyyyMMdd)

trigger: none
pr: none

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    displayName: "Testbed Name"
    default: vms3-t1-dx010-1

  - name: SAI_PTF_DOCKER
    type: string
    displayName: "SAI PTF DOCKER"
    default: docker-ptf-sai

  - name: SAI_REPO
    type: string
    displayName: "SAI Dev Repo"
    default: "opencomputeproject"

  - name: SAI_BRANCH
    type: string
    displayName: "SAI Dev Branch"
    default: "master"

  - name: JOB_CONFIG
    type: string
    displayName: "JOB CONFIG"
    default: "--disable_loganalyzer --sai_port_config=dx010-port_config.ini"

  # WorkFlow parameters
  - name: LOCK_TESTBED
    displayName: "Lock Testbed"
    type: boolean
    default: true
  
  - name: UPDATE_IMAGE
    displayName: "Update Image"
    type: boolean
    default: true

  - name: CHANGE_TOPO
    displayName: "Deploy non-topo"
    type: boolean
    default: true

  - name: RECOVER_TOPO
    displayName: "Recover Topo"
    type: boolean
    default: true
  
  - name: ENABLE_PTF_SAI_TEST
    displayName: "Run PTF-SAI Test"
    type: boolean
    default: false

  - name: ENABLE_BRCM_T0_TEST
    displayName: "Run Brcm T0 Test"
    type: boolean
    default: true

  - name: ENABLE_COMMUNITY_TEST
    displayName: "Run community test case"
    type: boolean
    default: false
 
  - name: ENABLE_WARM_REBOOT_TEST
    displayName: "Run warm reboot test"
    type: boolean
    default: false

  - name: RUN_TEST
    displayName: "Run Test"
    type: boolean
    default: true
  
  - name: UPLOAD_TEST_REPORT
    displayName: "Upload Test Report"
    type: boolean
    default: true

  # Upgrade parameters
  - name: IMAGE_URL
    type: string
    default: $(IMAGE_BRCM_202012)
    displayName: "Image URL"
    values: 
    - $(IMAGE_BRCM_202012)
    - $(IMAGE_BRCM_202012_SLIM)
    - $(IMAGE_BRCM_ABOOT_202012)
    - $(IMAGE_BRCM_ABOOT_202012_SLIM)
    - $(IMAGE_BRCM_PUBLIC)
    - $(IMAGE_BRCM_DBUG)
    - $(IMAGE_BRCM_ABOOT_PUBLIC)
    - $(IMAGE_BRCM_INTERNAL)
    - $(IMAGE_MLNX_INTERNAL)
    - $(IMAGE_BFN_ABOOT_INTERNAL)

  # Test Parameters
  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFTV2_BRCM_INTERNAL_202012)
    displayName: "py_saithrift URL"
    values: 
    - $(SAITHRIFT_BRCM_202012)
    - $(SAITHRIFT_BRCM_PUBLIC)
    - $(SAITHRIFT_BRCM_DBUG)
    - $(SAITHRIFT_MLNX_202012)
    - $(SAITHRIFT_MLNX_PUBLIC)
    - $(SAITHRIFTV2_BFN_INTERNAL_DBG)
    - $(SAITHRIFTV2_BRCM_202012_DBG)
    - $(SAITHRIFTV2_BRCM_INTERNAL_DBG)

stages:
  - template: ../templates/sai_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      LOCK_TESTBED: ${{ parameters.LOCK_TESTBED }}
      UPDATE_IMAGE: ${{ parameters.UPDATE_IMAGE }}
      CHANGE_TOPO: ${{ parameters.CHANGE_TOPO }}
      RECOVER_TOPO: ${{ parameters.RECOVER_TOPO }}
      ENABLE_PTF_SAI_TEST: ${{ parameters.ENABLE_PTF_SAI_TEST }}
      ENABLE_BRCM_T0_TEST: ${{ parameters.ENABLE_BRCM_T0_TEST }}
      ENABLE_COMMUNITY_TEST: ${{ parameters.ENABLE_COMMUNITY_TEST }}
      ENABLE_WARM_REBOOT_TEST: ${{ parameters.ENABLE_WARM_REBOOT_TEST }}
      RUN_TEST: ${{ parameters.RUN_TEST }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      SAI_PTF_DOCKER: ${{ parameters.SAI_PTF_DOCKER }}
      SAI_REPO: ${{ parameters.SAI_REPO }}
      SAI_BRANCH: ${{ parameters.SAI_BRANCH }}
      JOB_CONFIG: ${{ parameters.JOB_CONFIG }}
      UPLOAD_TEST_REPORT: ${{ parameters.UPLOAD_TEST_REPORT }}
