name: SAI_202012_RELEASE_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)
#Pipeline name Build.SAI.BRCM.4.3
trigger: none
pr: none

parameters:
  - name: BRCMSAI_BRANCH
    displayName: "brcm sai branch"
    type: string
    default: REL_4.3_202012

  # Self is mgmt-int, saibcm is acs-saibcm
  - name: saibcmrepo
    displayName: "BCM SAI Checkout Repo name"
    type: string
    default: saibcm

  - name: pool
    type: string
    displayName: "Resource pool"
    default: sonicbld

resources:
  repositories:
  - repository: saibcm
    type: git
    name: One/Networking-acs-saibcm
    ref: ${{ parameters.BRCMSAI_BRANCH }}
    endpoint: acs-saibcm
variables:
  - template: ../../templates/template_variables.yml

stages:
- stage: Build_Publish_BCMSAI
  jobs:
  - template: .pipelines/Build.template.yml@saibcm
    parameters:
      pool: ${{ parameters.pool }}
      saibcmrepo: ${{ parameters.saibcmrepo }}
