#Pipeline name Build.SAI.BRCM.Test.Artifact.4.3
trigger: none
pr: none

resources:
 pipelines:
   - pipeline: Build.SAI.BRCM.4.3
     source: Build.SAI.BRCM.4.3
     trigger:
        enabled: true
        branches:
          include:
          - '*'

parameters:
  - name: BUILDIMAGE_REPO
    displayName: "buildimage repo"
    type: string
    default: sonic-net

  - name: BUILDIMAGE_BRANCH
    displayName: "buildimage branch"
    type: string
    default: 202012

  - name: pool
    type: string
    displayName: "Resource pool"
    default: sonicbld

  - name: timeout
    type: number
    default: 120


jobs:
- job:
  displayName: Build SAI Test Artifact
  timeoutInMinutes: ${{ parameters.timeout }}
  pool: ${{ parameters.pool }}
  

  steps:
  - script: |
      set -ex

      mkdir -p publish
      rm -rf ./sonic-buildimage
      git init sonic-buildimage
      cd sonic-buildimage
      git remote add origin https://github.com/${{ parameters.BUILDIMAGE_REPO }}/sonic-buildimage.git
      git fetch origin
      git checkout -b ${{ parameters.BUILDIMAGE_BRANCH }} origin/${{ parameters.BUILDIMAGE_BRANCH }}

      make init
      NOSTRETCH=y NOJESSIE=y make configure PLATFORM=broadcom
      echo "==== Building brcm saiserverv2 docker and sai python header"
      make BLDENV=buster SAITHRIFT_V2=y INSTALL_DEBUG_TOOLS=y -f Makefile.work target/docker-saiserverv2-brcm.gz
      
      cp target/debs/buster/python-saithriftv2_0.9.4_amd64.deb ../publish
      cp target/debs/buster/libsaithriftv2-dev_0.9.4_amd64.deb ../publish
      cp target/debs/buster/saiserverv2_0.9.4_amd64.deb ../publish
      cp target/docker-saiserverv2-brcm.gz ../publish
      echo "==== Finished building brcm saiserverv2 docker and sai python header"
    displayName: "Build SAI Test Artifact"

  - publish: $(System.DefaultWorkingDirectory)/publish
    artifact: SAI.Test.Artifact
    displayName: "Publis SAI Test Artifact"
