name: NightlyTest_$(Build.DefinitionName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none


schedules:
  - cron: "0 4 * * 1,4"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal
    always: true

resources:
  repositories:
    - repository: sonic-mgmt
      type: github
      name: sonic-net/sonic-mgmt
      ref: master
      endpoint: sonic-net

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: AGENT_POOL
    type: string
    default: nightly
    values:
      - nightly
      - nightly2
      - nightly-svc
      - nightly-bjw
    displayName: "AGENT POOL"

  - name: TESTBED_NAME
    type: string
    default: "vms3-t1-dx010-1, vms20-t1-dx010-6"
    displayName: "Testbed Name"

  - name: IMAGE_URL
    type: string
    default: $(IMAGE_BRCM_INTERNAL)
    displayName: "Image URL"

  - name: UPGRADE_IMAGE_PARAM
    type: string
    default: "--always-power-cycle=True"
    displayName: "Upgrade image parameter"

  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFT_BRCM_INTERNAL)
    displayName: "py_saithrift URL"

  - name: MGMT_BRANCH
    type: string
    default: internal

  # Custom run scripts, if both SCRIPTS and FEATURES are empty, all the test will be executed
  - name: SCRIPTS
    type: string
    default: " "
    displayName: "Scripts to be executed"

  - name: FEATURES
    type: string
    default: " "
    displayName: "Features to be executed"

  # Custom skip scripts
  - name: SCRIPTS_EXCLUDE
    type: string
    default: "vrf/test_vrf.py, vrf/test_vrf_attr.py, mvrf/test_mgmtvrf.py, platform_tests/test_auto_negotiation.py, sflow/test_sflow.py, nat/test_dynamic_nat.py, nat/test_static_nat.py"
    displayName: "Scripts to be excluded"


  - name: FEATURES_EXCLUDE
    type: string
    default: " "
    displayName: "Features to be excluded"

  # Test timeout
  - name: MAX_RUN_TEST_MINUTES
    type: number
    default: 1800

  - name: REPO_NAME
    type: string
    default: "sonic-mgmt-int"

  - name: STOP_ON_FAILURE
    type: string
    default: False

  - name: RETRY_TIMES
    type: string
    default: 0

  - name: DUMP_KVM_IF_FAIL
    type: string
    default: False

  - name: REQUESTER
    type: string
    default: "Nightly Test"

stages:
- stage: Test

  variables:
    - group: SONiC-Elastictest

  jobs:
  - job:
    displayName: dx010.t1.internal.NightlyTest_by_Elastictest
    timeoutInMinutes: ${{ parameters.MAX_RUN_TEST_MINUTES }}
    continueOnError: false
    pool: ${{ parameters.AGENT_POOL }}
    steps:
    - template: .azure-pipelines/run-test-elastictest-template.yml@sonic-mgmt
      parameters:
        MIN_WORKER: 2
        MAX_WORKER: 2
        TEST_PLAN_TYPE: NIGHTLY
        PLATFORM: PHYSICAL
        TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
        SCRIPTS: ${{ parameters.SCRIPTS }}
        FEATURES: ${{ parameters.FEATURES }}
        SCRIPTS_EXCLUDE: ${{ parameters.SCRIPTS_EXCLUDE }}
        FEATURES_EXCLUDE: ${{ parameters.FEATURES_EXCLUDE }}
        COMMON_EXTRA_PARAMS: "--topology t1,any --py_saithrift_url=${{ parameters.PY_SAITHRIFT_URL }} --deep_clean --sad_case_list=sad_bgp,sad_lag_member,sad_lag,sad_vlan_port,sad_inboot"
        REPO_NAME: ${{ parameters.REPO_NAME }}
        MGMT_BRANCH: ${{ parameters.MGMT_BRANCH }}
        STOP_ON_FAILURE: ${{ parameters.STOP_ON_FAILURE }}
        RETRY_TIMES: ${{ parameters.RETRY_TIMES }}
        DUMP_KVM_IF_FAIL: ${{ parameters.DUMP_KVM_IF_FAIL }}
        REQUESTER: ${{ parameters.REQUESTER }}
        MAX_RUN_TEST_MINUTES: ${{ parameters.MAX_RUN_TEST_MINUTES }}
        IMAGE_URL: ${{ parameters.IMAGE_URL }}
        UPGRADE_IMAGE_PARAM: ${{ parameters.UPGRADE_IMAGE_PARAM }}
