---
- name: Restart Redis
  service:
    name: "redis"
    state: restarted
    enabled: yes
  delegate_to: "{{ connection_db_host }}"
  become: True

- name: Init connection db
  debug:
    msg: >
      Run 'init_connection_db'
      {{ lookup('servercfgd_client', 'init_connection_db', servercfgd_host=connection_db_host_ip) }}
