name: NightlyTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

# run on internal or private image
schedules:
  - cron: "0 1 * * SAT"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal
    always: true

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: vms29-t2-7250-1
    displayName: "Testbed Name"

  # Upgrade parameters
  # for now ignore updating the images on chassis
  - name: IMAGE_URL
    type: string
    default: $(IMAGE_BRCM_ABOOT_DNX_CHASSIS_202205)
    displayName: "Image URL"

  # Testbed specific, to skip and/or include directories
  - name: TESTBED_SPECIFIC
    type: string
    default: '-I "qos"'
    displayName: "Testbed specific"

  # Test Parameters
  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFT_BRCM_202205)
    displayName: "py_saithrift URL"

stages:
  - template: ../templates/nightly_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      NIGHTLY_TEST_TIMEOUT: 1440  # 48 hours