name: $(Build.DefinitionName)_Running_Init_$(Build.BuildId)_$(Date:yyyyMMdd)

trigger: none
pr: none

# schedules:
#   - cron: "0 7 * * 1,3"
#     displayName: Nightly SAI Testing Scheduler
#     branches:
#       include:
#         - internal
#     always: true

variables:
  - template: ../../../templates/template_variables.yml

parameters:
  - name: TESTBED_NAME
    type: string
    displayName: "Testbed Name"
    default: vms11-t0-s6000

  - name: LOCK_TESTBED_REASON
    displayName: "Lock Testbed Reason"
    type: string
    default: "SAI Warm Reboot v1.7 Nightly Test - T0"

  - name: IMAGE_URL
    type: string
    default: $(IMAGE_BRCM_202012)
    displayName: "Image URL"

  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFTV2_BRCM_INTERNAL_202012)
    displayName: "py_saithrift URL"

  - name: SAI_REPO
    type: string
    displayName: "SAI Dev Repo"
    default: "opencomputeproject"

  # WorkFlow parameters
  - name: ENABLE_BRCM_T0_TEST
    displayName: "Run Brcm T0 Test"
    type: boolean
    default: false

  - name: ENABLE_T0_WARM_REBOOT_TEST
    displayName: "Run Brcm T0 Warm Reboot Test"
    type: boolean
    default: true

  - name: JOB_CONFIG
    type: string
    displayName: "JOB CONFIG"
    default: " "

  # Checkout sai_qualify/ folder from public
  - name: OVERWRITE_INTERNAL_MGMT
    displayName: "overwrite internal sonic-mgmt sai_qualify/ folder"
    type: boolean
    default: true

  - name: MGMT_REPO
    displayName: "sonic-mgmt repo"
    type: string
    default: "zhiyuan0112"

  - name: MGMT_BRANCH
    displayName: "sonic-mgmt branch"
    type: string
    default: "zhiyuan_warmreboot2"

stages:
- stage: RunSAITest
  jobs:
  - template: ../../../templates/sai_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      LOCK_TESTBED_REASON: ${{ parameters.LOCK_TESTBED_REASON }}
      ENABLE_BRCM_T0_TEST: ${{ parameters.ENABLE_BRCM_T0_TEST }}
      ENABLE_T0_WARM_REBOOT_TEST: ${{ parameters.ENABLE_T0_WARM_REBOOT_TEST }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      SAI_REPO: ${{ parameters.SAI_REPO }}
      JOB_CONFIG: ${{ parameters.JOB_CONFIG }}
      OVERWRITE_INTERNAL_MGMT: ${{ parameters.OVERWRITE_INTERNAL_MGMT }}
      MGMT_REPO: ${{ parameters.MGMT_REPO }}
      MGMT_BRANCH: ${{ parameters.MGMT_BRANCH }}
