name: NightlyTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

schedules:
  - cron: "0 11 * * 5"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal
    always: true

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: bjw-vms6-t1-lag-ec9516-1
    displayName: "Testbed Name"

  # Upgrade parameters
  - name: IMAGE_URL
    type: string
    default: $(BJW_IMAGE_BFN_INTERNAL)
    displayName: "Image URL"

  # Test Parameters
  - name: PY_SAITHRIFT_URL
    type: string
    default: $(BJW_SAITHRIFT_BFN_INTERNAL)
    displayName: "py_saithrift URL"

  - name: EXTRA_PARAMS
    type: string
    default: "--no_dscp_uniform"
    displayName: "Extra pytest params"

  - name: SKIP_SCRIPTS
    type: string
    default: "platform_tests/link_flap/test_cont_link_flap.py"
    displayName: "Skip Scripts"

  - name: SKIP_TEST_RESULTS_UPLOADING
    type: boolean
    default: false
    displayName: "Skip uploading test results to Kusto"

  - name: AGENT_POOL
    type: string
    default: nightly-bjw
    displayName: "Agent pool"

stages:
  - template: ../templates/nightly_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      EXTRA_PARAMS: ${{ parameters.EXTRA_PARAMS }}
      SKIP_SCRIPTS: ${{ parameters.SKIP_SCRIPTS }}
      SKIP_TEST_RESULTS_UPLOADING: ${{ parameters.SKIP_TEST_RESULTS_UPLOADING }}
      AGENT_POOL: ${{ parameters.AGENT_POOL }}
