name: NightlyTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

schedules:
  - cron: "0 15 * * 0,2,4"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal-202012
    always: true

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: vms21-dual-t0-7260
    displayName: "Testbed Name"

  # Upgrade parameters
  - name: IMAGE_URL
    type: string
    default: $(IMAGE_BRCM_ABOOT_202012)
    displayName: "Image URL"

  # Deploy parameters
  - name: ENABLE_DATAACL
    type: boolean
    default: false

  # Test Parameters
  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFT_BRCM_202012)
    displayName: "py_saithrift URL"

  - name: SKIP_SCRIPTS
    type: string
    default: "platform_tests/test_cont_warm_reboot.py"
    displayName: "Skip Scripts"

  - name: TESTBED_SPECIFIC
    type: string
    default: '-S "span sub_port_interfaces dualtor_io platform_tests"'
    displayName: Testbed specific

  - name: SKIP_TEST_RESULTS_UPLOADING
    type: boolean
    default: false
    displayName: "Skip uploading test results to Kusto"

stages:
  - template: ../templates/nightly_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      ENABLE_DATAACL: ${{ parameters.ENABLE_DATAACL }}
      SKIP_SCRIPTS: ${{ parameters.SKIP_SCRIPTS }}
      TESTBED_SPECIFIC: ${{ parameters.TESTBED_SPECIFIC }}
      SKIP_TEST_RESULTS_UPLOADING: ${{ parameters.SKIP_TEST_RESULTS_UPLOADING }}
