
parameters:
- name: BASE_DIR
  type: string
  default: ""

steps:

  - script: |
      access_token=`curl -X POST -s \
          -d 'grant_type=client_credentials&client_id=$(TBSHARE_AAD_CLIENT_ID)&client_secret=$(TBSHARE_AAD_CLIENT_SECRET)&resource=https://vault.azure.net' \
          "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token" | jq -r .access_token`

      nm_secrets=`curl -X GET -s -H "Authorization: Bearer $access_token" \
          "https://sonic.vault.azure.net/secrets/nm-secrets?api-version=7.3" | jq -r .value`

      ansible_vault_passwd=`curl -X GET -s -H "Authorization: Bearer $access_token" \
          "https://sonic.vault.azure.net/secrets/ansible-vault-passwd?api-version=7.3" | jq -r .value`

      echo "$nm_secrets" > $PWD/${{ parameters.BASE_DIR }}/ansible/group_vars/all/secrets.json
      echo "$ansible_vault_passwd" > $PWD/${{ parameters.BASE_DIR }}/ansible/password.txt

      # decrypt the secret file
      md5sum $PWD/${{ parameters.BASE_DIR }}/ansible/group_vars/all/secrets.json
      ansible-vault decrypt $PWD/${{ parameters.BASE_DIR }}/ansible/group_vars/all/secrets.json --vault-password-file=$PWD/${{ parameters.BASE_DIR }}/ansible/password.txt
      rc=$?
      if [[ $rc != 0 ]]; then
          http_proxy='' https_proxy='' curl -s http://172.17.0.1:8000/secrets.json > $PWD/${{ parameters.BASE_DIR }}/ansible/group_vars/all/secrets.json
      fi
    displayName: Get secrets
