
parameters:
- name: BASE_DIR
  type: string
  default: ""

steps:

  - script: |
      pwd

      echo "$nm_secrets" > $PWD/${{ parameters.BASE_DIR }}/ansible/group_vars/all/secrets.json
      echo "$ansible_vault_passwd" > $PWD/${{ parameters.BASE_DIR }}/ansible/password.txt

      # decrypt the secret file
      md5sum $PWD/${{ parameters.BASE_DIR }}/ansible/group_vars/all/secrets.json
      ansible-vault decrypt $PWD/${{ parameters.BASE_DIR }}/ansible/group_vars/all/secrets.json --vault-password-file=$PWD/${{ parameters.BASE_DIR }}/ansible/password.txt
    env:
        nm_secrets: $(nm-secrets)
        ansible_vault_passwd: $(ansible-vault-passwd)
    displayName: Get secrets
