name: NightlyTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none


schedules:
  - cron: "0 14 * * 0,1,2,3,4,5"
    displayName: Nightly Scheduler
    branches:
      include:
        - internal
    always: true

variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: "vms28-t0-4600c-03, vms28-t0-4600c-04"
    displayName: "Testbed Name"

  - name: IMAGE_URL
    type: string
    default: $(IMAGE_MLNX_202012)
    displayName: "Image URL"

  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFT_MLNX_202012)
    displayName: "py_saithrift URL"

  # Custom run scripts, if both SCIPTS and FEATURES are empty, all the test will be executed
  - name: SCRIPTS
    type: string
    default: " "
    displayName: "Scripts to be executed"

  - name: FEATURES
    type: string
    default: " "
    displayName: "Features to be executed"

  # Custom skip scripts
  - name: SCRIPTS_EXCLUDE
    type: string
    default: "vrf/test_vrf.py, vrf/test_vrf_attr.py, mvrf/test_mgmtvrf.py, platform_tests/test_auto_negotiation.py, sflow/test_sflow.py, nat/test_dynamic_nat.py, nat/test_static_nat.py, vrf/test_vrf.py, vrf/test_vrf_attr.py"
    displayName: "Scripts to be excluded"

  - name: FEATURES_EXCLUDE
    type: string
    default: " "
    displayName: "Features to be excluded"

  # Test timeout
  - name: NIGHTLY_TEST_TIMEOUT
    type: number
    default: 1920

stages:
  - template: ../../../run-test-scheduler-template.yml
    parameters:
      TOPOLOGY: t0-64
      MIN_WORKER: 2
      MAX_WORKER: 2
      TEST_PLAN_TYPE: NIGHTLY
      PLATFORM: PHYSICAL
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      SCRIPTS: ${{ parameters.SCRIPTS }}
      FEATURES: ${{ parameters.FEATURES }}
      SCRIPTS_EXCLUDE: ${{ parameters.SCRIPTS_EXCLUDE }}
      FEATURES_EXCLUDE: ${{ parameters.FEATURES_EXCLUDE }}
      COMMON_EXTRA_PARAMS: "--topology t0,any --py_saithrift_url=${{ parameters.PY_SAITHRIFT_URL }}"
