name: NightlyTest_$(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

# run on internal or private image
variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

parameters:
  - name: TESTBED_NAME
    type: string
    default: vms29-t2-8800-3
    displayName: "Testbed Name"

  # Upgrade parameters
  # for now ignore updating the images on chassis
  - name: IMAGE_URL
    type: string
    default: ""
    displayName: "Image URL"

  # Testbed specific parameters
  - name: TESTBED_SPECIFIC
    type: string
    default: '-S "qos voq"'
    displayName: "Testbed specific"

  # Test Parameters
  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFT_BRCM_201911)
    displayName: "py_saithrift URL"

  # Testbed specific, skip unsupported test cases
  # Unsupported platform API test cases are skipped
  - name: SKIP_SCRIPTS
    type: string
    default: ""
    displayName: "Skip Scripts"

stages:
  - template: ../templates/nightly_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      SKIP_SCRIPTS: ${{ parameters.SKIP_SCRIPTS }}
      TESTBED_SPECIFIC: ${{ parameters.TESTBED_SPECIFIC }}
