# This job is for periodically polling testbed health and upload polling results to Kusto

name: $(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

schedules:
  - cron: "0 2 * * *"
    displayName: TestFailureAnalyzingScheduler
    branches:
      include:
        - internal
    always: true

parameters:
  - name: NEW_ICM_NUMBER_LIMIT
    type: number
    default: 30
    displayName: "The maximum number of new IcM for this run."

stages:
  - stage: TestFailureAnalyzing
    jobs:
      - job: TestFailureAnalyzing
        pool: nightly
        timeoutInMinutes: 240
        variables:
          - group: KUSTO_SECRETS
          - group: GIT_SECRETS
          - name: skipComponentGovernanceDetection
            value: true

        steps:

          - template: ../.azure-pipelines/nightly/templates/get_secrets.yml

          - task: Bash@3
            displayName: Run analyzer script
            inputs:
              targetType: 'inline'
              script: |
                set -x

                source /var/AzDevOps/env-python3/bin/activate

                cd test_analyzer
                pip3 install -r requirements.txt

                python3 test_failure_analyzer.py -n ${{ parameters.NEW_ICM_NUMBER_LIMIT }}
            env:
              TEST_REPORT_INGEST_KUSTO_CLUSTER_BACKUP: $(TEST_REPORT_INGEST_KUSTO_CLUSTER_BACKUP)
              TEST_REPORT_AAD_TENANT_ID_BACKUP: $(TEST_REPORT_AAD_TENANT_ID_BACKUP)
              TEST_REPORT_AAD_CLIENT_ID_BACKUP: $(TEST_REPORT_AAD_CLIENT_ID_BACKUP)
              TEST_REPORT_AAD_CLIENT_KEY_BACKUP: $(TEST_REPORT_AAD_CLIENT_KEY_BACKUP)
              AZURE_DEVOPS_MSAZURE_TOKEN: $(AZURE_DEVOPS_MSAZURE_TOKEN)
