parameters:
  - name: TESTBED_NAME
    type: string
    displayName: "Testbed Name for SAI test"
    default: vms3-t1-dx010-1

  - name: TESTBED_NAME_FOR_SONIC
    type: string
    displayName: "Testbed Name for SONiC test"
    default: vms20-t1-dx010-6

  - name: IMAGE_URL
    type: string
    default: $(IMAGE_BRCM_202012)
    displayName: "Image URL"
    values:
    - $(IMAGE_BRCM_202012)
    - $(IMAGE_BRCM_202012_SLIM)
    - $(IMAGE_BRCM_ABOOT_202012)
    - $(IMAGE_BRCM_ABOOT_202012_SLIM)
    - $(IMAGE_BRCM_202205)
    - $(IMAGE_BRCM_202205_SLIM)
    - $(IMAGE_BRCM_ABOOT_202205)
    - $(IMAGE_BRCM_ABOOT_202205_SLIM)
    - $(IMAGE_BRCM_INTERNAL)
    - $(IMAGE_BRCM_ABOOT_INTERNAL)
    - $(IMAGE_BRCM_PUBLIC)
    - $(IMAGE_BRCM_DBUG)
    - $(IMAGE_BRCM_ABOOT_PUBLIC)

  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFTV2_BRCM_INTERNAL_202012)
    displayName: "py_saithrift URL"
    values:
    - $(SAITHRIFT_BRCM_202012)
    - $(SAITHRIFT_BRCM_PUBLIC)
    - $(SAITHRIFT_BRCM_DBUG)
    - $(SAITHRIFT_MLNX_202012)
    - $(SAITHRIFT_MLNX_PUBLIC)
    - $(SAITHRIFTV2_BFN_INTERNAL_DBG)
    - $(SAITHRIFTV2_BRCM_202012_DBG)
    - $(SAITHRIFTV2_BRCM_INTERNAL_DBG)
    - $(SAITHRIFTV2_BRCM_INTERNAL_202012)
    - $(SAITHRIFTV2_BRCM_INTERNAL_202205)

 # Deploy SAI SDK
  - name: DEPLOY_SAI_SDK
    displayName: "Build and deploy sai sdk"
    type: boolean
    default: true

  - name: BRCMSAI_BRANCH
    displayName: "brcm sai branch"
    type: string
    default: REL_4.3.5.2_pre

  - name: SDK_ARTIFACT_NAME
    displayName: "artifact name"
    type: string
    default: saibcm.4_3

  - name: SAI_REPO
    type: string
    displayName: "SAI Dev Repo"
    default: "opencomputeproject"

  - name: SAI_BRANCH
    type: string
    displayName: "SAI Dev Branch"
    default: "master"

  # Deploy vscode in PTF
  - name: PTF_DEPLOY_VSCODE
    displayName: "Deploy Vscode in PTF"
    type: boolean
    default: false

  # WorkFlow parameters
  - name: LOCK_TESTBED
    displayName: "Lock Testbed"
    type: boolean
    default: true

  - name: CHANGE_TOPO
    displayName: "Deploy non-topo"
    type: boolean
    default: true

  - name: PREPARE_SAI_TB
    displayName: "Prepare SAI Test Env"
    type: boolean
    default: true

  - name: UPDATE_IMAGE
    displayName: "Update Image"
    type: boolean
    default: true

  - name: RECOVER_TB
    displayName: "Recover Testbed"
    type: boolean
    default: true

  - name: ENABLE_PTF_SAI_TEST
    displayName: "Run PTF-SAI Test"
    type: boolean
    default: false

  - name: ENABLE_BRCM_T0_TEST
    displayName: "Run Brcm T0 Test"
    type: boolean
    default: true

  - name: ENABLE_COMMUNITY_TEST
    displayName: "Run community test case"
    type: boolean
    default: false

  - name: ENABLE_WARM_REBOOT_TEST
    displayName: "Run warm reboot test"
    type: boolean
    default: false

  - name: UPLOAD_TEST_REPORT
    displayName: "Upload Test Report"
    type: boolean
    default: false

  # Self is mgmt-int, saibcm is acs-saibcm
  - name: saibcmrepo
    displayName: "BCM SAI Checkout Repo name"
    type: string
    default: saibcm

  - name: pool
    type: string
    displayName: "Resource pool"
    default: sonicbld

  - name: SAI_PTF_DOCKER
    type: string
    displayName: "SAI PTF DOCKER"
    default: docker-ptf-sai

  - name: JOB_CONFIG
    type: string
    displayName: "JOB CONFIG"
    default: "--disable_loganalyzer --sai_port_config=port_config.ini"

  # Checkout sai_qualify/ folder from public
  - name: OVERWRITE_INTERNAL_MGMT
    displayName: "overwrite internal sonic-mgmt sai_qualify/ folder"
    type: boolean
    default: true

  - name: MGMT_REPO
    displayName: "sonic-mgmt repo"
    type: string
    default: "sonic-net"
  
  - name: MGMT_BRANCH
    displayName: "sonic-mgmt branch"
    type: string
    default: "master"

resources:
  repositories:
  - repository: saibcm
    type: git
    name: One/Networking-acs-saibcm
    ref: ${{ parameters.BRCMSAI_BRANCH }}
    endpoint: acs-saibcm
variables:
  - group: SONIC_IMAGE_URLS
  - group: SAITHRIFT_URLS

stages:
- stage: Build_Publish_BCMSAI
  condition: ${{ parameters.DEPLOY_SAI_SDK }}
  jobs:
  - template: .pipelines/Build.template.yml@saibcm
    parameters:
      pool: ${{ parameters.pool }}
      saibcmrepo: ${{ parameters.saibcmrepo }}

- stage: Run_Test
  jobs:
    - job: Run_SAI_Test
    - template: ../nightly/templates/sai_test.yml
      parameters:
        TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
        LOCK_TESTBED: ${{ parameters.LOCK_TESTBED }}
        PREPARE_SAI_TB: ${{ parameters.PREPARE_SAI_TB }}
        UPDATE_IMAGE: ${{ parameters.UPDATE_IMAGE }}
        CHANGE_TOPO: ${{ parameters.CHANGE_TOPO }}
        RECOVER_TB: ${{ parameters.RECOVER_TB }}
        ENABLE_PTF_SAI_TEST: ${{ parameters.ENABLE_PTF_SAI_TEST }}
        ENABLE_BRCM_T0_TEST: ${{ parameters.ENABLE_BRCM_T0_TEST }}
        ENABLE_COMMUNITY_TEST: ${{ parameters.ENABLE_COMMUNITY_TEST }}
        ENABLE_WARM_REBOOT_TEST: ${{ parameters.ENABLE_WARM_REBOOT_TEST }}
        RUN_TEST: ${{ or(or(parameters.ENABLE_PTF_SAI_TEST, parameters.ENABLE_BRCM_T0_TEST), or( parameters.ENABLE_COMMUNITY_TEST, parameters.ENABLE_WARM_REBOOT_TEST )) }}
        PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
        IMAGE_URL: ${{ parameters.IMAGE_URL }}
        SAI_PTF_DOCKER: ${{ parameters.SAI_PTF_DOCKER }}
        SAI_REPO: ${{ parameters.SAI_REPO }}
        SAI_BRANCH: ${{ parameters.SAI_BRANCH }}
        JOB_CONFIG: ${{ parameters.JOB_CONFIG }}
        UPLOAD_TEST_REPORT: ${{ parameters.UPLOAD_TEST_REPORT }}
        DEPLOY_SAI_SDK: ${{ parameters.DEPLOY_SAI_SDK }}
        SDK_ARTIFACT_NAME: ${{ parameters.SDK_ARTIFACT_NAME }}
        PTF_DEPLOY_VSCODE: ${{ parameters.PTF_DEPLOY_VSCODE }}
        OVERWRITE_INTERNAL_MGMT: ${{ parameters.OVERWRITE_INTERNAL_MGMT }}
        MGMT_REPO: ${{ parameters.MGMT_REPO }}
        MGMT_BRANCH: ${{ parameters.MGMT_BRANCH }}

    - job: Run_SONiC_Test
    - template: ../nightly/templates/sonic_test_for_sai.yml
      parameters:
        TESTBED_NAME: ${{ parameters.TESTBED_NAME_FOR_SONIC }}
        LOCK_TESTBED: ${{ parameters.LOCK_TESTBED }}
        UPDATE_IMAGE: ${{ parameters.UPDATE_IMAGE }}
        PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
        IMAGE_URL: ${{ parameters.IMAGE_URL }}
        UPLOAD_TEST_REPORT: ${{ parameters.UPLOAD_TEST_REPORT }}
        DEPLOY_SAI_SDK: ${{ parameters.DEPLOY_SAI_SDK }}
        SDK_ARTIFACT_NAME: ${{ parameters.SDK_ARTIFACT_NAME }}
