name: $(Build.DefinitionName)_Running_Init_$(Build.BuildId)_$(Date:yyyyMMdd)

trigger: none
pr: none

variables:
  - template: ./templates/template_variables.yml

parameters:
  - name: TESTBED_NAME
    type: string
    displayName: "Testbed Name"
    default: vms11-t0-s6000

  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFTV2_BRCM_INTERNAL_202012)
    displayName: "py_saithrift URL"

  - name: SAI_REPO
    type: string
    displayName: "SAI Dev Repo"
    default: "opencomputeproject"

  - name: SAI_BRANCH
    type: string
    displayName: "SAI Dev Branch"
    default: "master"

  - name: JOB_CONFIG
    type: string
    displayName: "JOB CONFIG"
    default: " "

  #Resource agent pool
  - name: AGENT_POOL
    displayName: "Resource agent pool"
    type: string
    default: nightly
    values:
      - nightly
      - nightly2
      - nightly-svc
      - nightly-bjw

  - name: SCAN_CASES
    displayName: "Scan and Upload"
    type: boolean
    default: true

stages:
- stage: RunSAITest
  jobs:
  - template: templates/sai_case_scanner.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      SAI_REPO: ${{ parameters.SAI_REPO }}
      SAI_BRANCH: ${{ parameters.SAI_BRANCH }}
      JOB_CONFIG: ${{ parameters.JOB_CONFIG }}
      AGENT_POOL: ${{ parameters.AGENT_POOL }}
      SCAN_CASES: ${{ parameters.SCAN_CASES }}
