- name: activate cisco config
  activate_cisco: telnet_port={{ serial_port }}
                   login={{ cisco_login }}
                   password={{ cisco_password }}
  register: activate_output
  until: '"activate_code" in activate_output and activate_output.activate_code == 0'
  retries: 5
  delay: 10

