name: $(Build.DefinitionName)_Running_Init_$(Build.BuildId)_$(Date:yyyyMMdd)

trigger: none
pr: none

# schedules:
#   - cron: "0 12 * * 1,3"
#     displayName: Nightly SAI Testing Scheduler
#     branches:
#       include:
#         - internal
#     always: true

variables:
  - template: ../../templates/template_variables.yml

parameters:
  - name: TESTBED_NAME
    type: string
    displayName: "Testbed Name"
    default: testbed-bjw-slx-can-1

  - name: LOCK_TESTBED_REASON
    displayName: "Lock Testbed Reason"
    type: string
    default: "SAI v1.7 Nightly Test - T0"

  - name: IMAGE_URL
    type: string
    default: $(IMAGE_BRCM_202012_BJ)
    displayName: "Image URL"

  - name: PY_SAITHRIFT_URL
    type: string
    default: $(SAITHRIFTV2_BRCM_INTERNAL_202012_BJ)
    displayName: "py_saithrift URL"

  - name: SAI_REPO
    type: string
    displayName: "SAI Dev Repo"
    default: "opencomputeproject"

  # WorkFlow parameters
  - name: ENABLE_PTF_SAI_TEST
    displayName: "Run PTF-SAI Test"
    type: boolean
    default: false

  - name: ENABLE_BRCM_T0_TEST
    displayName: "Run Brcm T0 Test"
    type: boolean
    default: true

  - name: JOB_CONFIG
    type: string
    displayName: "JOB CONFIG"
    default: " "

  #Resource agent pool
  - name: AGENT_POOL
    displayName: "Resource agent pool"
    type: string
    default: nightly-bjw

stages:
- stage: RunSAITest
  jobs:
  - template: ../../templates/sai_test.yml
    parameters:
      TESTBED_NAME: ${{ parameters.TESTBED_NAME }}
      LOCK_TESTBED_REASON: ${{ parameters.LOCK_TESTBED_REASON }}
      ENABLE_PTF_SAI_TEST: ${{ parameters.ENABLE_PTF_SAI_TEST }}
      ENABLE_BRCM_T0_TEST: ${{ parameters.ENABLE_BRCM_T0_TEST }}
      PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
      IMAGE_URL: ${{ parameters.IMAGE_URL }}
      SAI_REPO: ${{ parameters.SAI_REPO }}
      JOB_CONFIG: ${{ parameters.JOB_CONFIG }}
      AGENT_POOL: ${{ parameters.AGENT_POOL }}
